spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariCP-Pool
      idle-timeout: 30000
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 5
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
