spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/mybatis-plus?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
    username: root
    password:
    # hikari连接池配置参考:https://blog.csdn.net/qq_32953079/article/details/81502237
    hikari:
      connection-test-query: SELECT 1
      # 等待来自池的连接的最大毫秒数（默认：30S）
      connection-timeout: 30000
      # 池中连接最长生命周期（默认：30分钟）
      max-lifetime: 1800000
      pool-name: HikariCP-Pool
      # 连接允许在池中闲置的最长时间（默认：1分钟）
      idle-timeout: 30000
      # 自动提交从池中返回的连接（默认:true）
      auto-commit: true
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 15
      # 池中维护的最小空闲连接数
      minimum-idle: 5
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml